name: Main

on:
  push:
    branches: [main]
    tags:
      - v[0-9]*
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn build

  publish-npm:
    if: github.ref == 'refs/heads/main'
    needs: [build, lint]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: NPM login
        run: |
          npm install -g npm-cli-login npm
          npm-cli-login -r https://registry.npmjs.org -s @subrelay --config-path ~/.npmrc
        env:
          NPM_USER: ${{ secrets.NPM_USERNAME }}
          NPM_PASS: ${{ secrets.NPM_PASSWORD }}
          NPM_EMAIL: 'ttdiemchi@gmail.com'
      - run: npm ci
      - run: npm publish --access=public
