name: 🚀 Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build
        run: pnpm build

      - name: 📝 Version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: pnpm version ${TAG_NAME} --no-git-tag-version

      - name: 🐙 Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_NODE_AUTH_TOKEN }}
        run: |
          pnpm publish --no-git-checks